🐛: Add explicit type annotation to assertXxxError (#37)
## 🤔 What was the issue

When I use assertXxxError in catch clause, following type error occurs.

```console
src/bases/core/errors/ApplicationError.ts:29:5 - error TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.

29     assertApplicationError(e);
       ~~~~~~~~~~~~~~~~~~~~~~

  src/bases/core/errors/ApplicationError.ts:23:14
    23 export const assertApplicationError = assertInstanceOf(ApplicationError);
                    ~~~~~~~~~~~~~~~~~~~~~~
    'assertApplicationError' needs an explicit type annotation.
```

Source code is below.

```tsx
const process = () => {
  try {
    throw new ApplicationError();
  } catch (e) {
    assertApplicationError(e);
  }
};
```

## 🐛 What was the cause

I don't fully understand it, but it seems that when using assertions,
explicit type annotation for the target function must be declared.

## ✅ How it was resolved

- [x] Add type annotation for existing error assertion function
- [x] Add type annotation for the error class template